# Cell connected to V1/I2
cell1:
  # Name of cell
  name: test1
  # Associated TEROS12 sensor ID
  teros: 0

# Cell connected to V2/I2
cell2:
  # Name of cell
  name: test2
  # Associated TEROS12 sensor ID
  teros: 0

# Measure from teros
teros: true
# Serial port connected to Arduino monitoring TEROS-12 sensor
teros_port: /dev/ttyUSB1

# Interval in seconds between uploads
interval: 3600

# Backup data to file on SD card
backup: true
# Folder to backup to (optional). If not defined, defaults to 
backup_folder: ./

# Upload method, can be the following literals ["lora", "eth", "none"]
method: lora

# Serial port connected to LoRa module
lora_port: /dev/ttyUSB0