# Cell connected to V1/I2
cell1:
  # Name of cell
  name: test1
  # Associated TEROS12 sensor ID
  teros: 0

# Cell connected to V2/I2
cell2:
  # Name of cell
  name: test2
  # Associated TEROS12 sensor ID
  teros: 0


# Interval in seconds between uploads
interval: 3600

# Backup data to file on SD card
backup: false

# Upload method, either "lora" or "ethernet"
method: lora

# Serial port connected to LoRa module
lora_port: /dev/ttyUSB0
# Serial port connected to Arduino monitoring TEROS-12 sensor
teros_port: /dev/ttyUSB1