# Name of cell connected to channels V1 and I1
name1: test1
# Name of cell connected to channels V2 and I2
name2: test2

# Mapping of cell names to TEROS-12 soil moisture sensor ids. Cell names are NOT
# limited to measured cells.
teros:
  test1: 0
  test2: 0

# Interval in seconds between uploads
interval: 3600

# Upload method, either "lora" or "ethernet"
method: lora

# Serial port connected to LoRa module
lora_port: /dev/ttyUSB0
# Serial port connected to Arduino monitoring TEROS-12 sensor
teros_port: /dev/ttyUSB1