---
- name: Fetch data from RocketLoggers
  hosts: rocketloggers
  tasks:
    - name: Find data files
      ansible.builtin.find:
        paths: "/media/sdcard/uploader"
        patterns: "*.csv"
      register: data_files

    - name: Copy files to local computer
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "./data/"
        flat: true
      with_items: "{{ data_files.files }}"
