---
- name: Install RocketLogger firmware
  hosts: rocketloggers
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

    - name: Install required system packages
      become: true
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - python3-setuptools
          - python3-numpy
          - python3-requests
          - fake-hwclock
        update_cache: true

    - name: Enable fake-hwclock
      become: true
      ansible.builtin.systemd:
        name: fake-hwclock.service
        state: started
        enabled: true
        daemon_reload: true

    - name: Add user rocketlogger to dialout
      become: true
      ansible.builtin.user:
        name: rocketlogger
        groups: dialout
        append: true

    - name: Update pip
      become: true
      ansible.builtin.pip:
        name: pip
        state: latest

    - name: Uninstall RocketLogger firmware
      become: true
      ansible.builtin.pip:
        name: rocketlogger-dirtviz-uploader
        state: absent

    - name: Install firmware package
      become: true
      ansible.builtin.pip:
        name: 'git+https://github.com/jlab-sensing/Rocketlogger-Firmware.git'
        state: latest

    - name: Copy config file
      become: true
      ansible.builtin.copy:
        src: uploader.yaml
        dest: /etc/uploader.yaml
        owner: rocketlogger
        group: rocketlogger
        mode: '0644'
        force: false

    - name: Create data directory
      become: true
      ansible.builtin.file:
        path: /media/sdcard/uploader
        state: directory
        mode: '0777'
        owner: rocketlogger
        group: rocketlogger

    - name: Install service file
      become: true
      ansible.builtin.copy:
        src: uploader.service
        dest: /etc/systemd/system/uploader.service
        owner: root
        group: root
        mode: '0644'
        backup: true

    - name: Enable and Start service
      become: true
      ansible.builtin.systemd:
        name: uploader.service
        state: started
        enabled: true
        daemon_reload: true
